import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import SideBar from "@/components/SideBar";
import HeaderDashboard from "@/containers/Dashboard/HeaderDashboard";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex h-screen bg-gray-100">
      <SideBar />
      <div className="flex-1 flex flex-col overflow-hidden ">
        <main className="flex-1 overflow-x-hidden overflow-y-auto ">
          <HeaderDashboard />
          {children}
        </main>
      </div>
    </div>
  );
}
